# Configurações do Banco H2 (Exigência do PDF)
spring.datasource.url=jdbc:h2:mem:soundlistdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#datasource:
#driver-class-name: com.mysql.cj.jdbc.Driver
#url:
#username: root
#password: thiago